[log]
#level = "INFO"

[postgresql]
#pgdata = "pgdata"
#database = "postgres"
#host = "/tmp"
#mode = "auto"
#password = ""
#poll-interval = "1s"
#port = 5432
#user = "postgres"

[postgresql.wal]
#readahead-bytes = "32MiB"

[postgresql.xlog]
#mode = "pg"
#pg_waldump-path = "/usr/local/bin/pg_waldump"

[run]
# log-format specifies the type of logs to emit.  Valid log formats include:
#
# * "auto" - change the default logging format to be "json" or "human" depending
#   on whether or not stdout is a TTY.  If stdout is a TTY, "auto" will
#   automatically change to "human", otherwise it will select "json."
# * "json" - Zerolog default JSON output
# * "human" - Human-friendly log output
#log-format = "auto"
#
#num-io-threads = 1500
#retry-db-init = false
#
# use-color changes its default depending on whether or not stdout is a TTY.
# If stdout is a TTY the default changes to true.
#use-color = false
